//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MensErgerJeNiet
{
	public virtual dobbelsteen dobbelsteen
	{
		get;
		set;
	}

	public virtual bord bord
	{
		get;
		set;
	}

	public virtual void Speel(object Speler)
	{
		throw new System.NotImplementedException();
	}

}

