//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class pion
{
	public virtual object kleur
	{
		get;
		set;
	}

	public virtual object positie
	{
		get;
		set;
	}

	public virtual hand hand
	{
		get;
		set;
	}

	public virtual VeldStatus VeldStatus
	{
		get;
		set;
	}

	public virtual void verplaatsen()
	{
		throw new System.NotImplementedException();
	}

}

