//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Speler
{
	public virtual object id
	{
		get;
		set;
	}

	public virtual object naam
	{
		get;
		set;
	}

	public virtual object Kleur
	{
		get;
		set;
	}

	public virtual dobbelsteen dobbelsteen
	{
		get;
		set;
	}

	public virtual hand hand
	{
		get;
		set;
	}

	public virtual IEnumerable<MensErgerJeNiet> MensErgerJeNiet
	{
		get;
		set;
	}

}

